# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [28]:
import pandas as pd

data = {
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'price': [1200, 25, 75, 300, 50],
    'stock rating': [8, 9, 7, 6, 8]
}

df = pd.DataFrame(data)
display(df)

    product  price  stock rating
0    Laptop   1200             8
1     Mouse     25             9
2  Keyboard     75             7
3   Monitor    300             6
4    Webcam     50             8

In [29]:
# Use sort_values(by='col') to sort by column values.
df.sort_values(by='price')

    product  price  stock rating
1     Mouse     25             9
4    Webcam     50             8
2  Keyboard     75             7
3   Monitor    300             6
0    Laptop   1200             8

In [30]:
df.sort_values(by='price', ascending=False, inplace = False)

    product  price  stock rating
0    Laptop   1200             8
3   Monitor    300             6
2  Keyboard     75             7
4    Webcam     50             8
1     Mouse     25             9

In [31]:
# Sort by multiple columns by passing a list.
df.sort_values(by=['price', 'stock rating'], ascending = [True, False])

    product  price  stock rating
1     Mouse     25             9
4    Webcam     50             8
2  Keyboard     75             7
3   Monitor    300             6
0    Laptop   1200             8

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [32]:
# mean
df.mean(numeric_only= True)

price           330.0
stock rating      7.6
dtype: float64

In [33]:
# column-wise mean
df['price'].mean()

np.float64(330.0)

In [34]:
# describe()
df.describe()

             price  stock rating
count     5.000000      5.000000
mean    330.000000      7.600000
std     498.560428      1.140175
min      25.000000      6.000000
25%      50.000000      7.000000
50%      75.000000      8.000000
75%     300.000000      8.000000
max    1200.000000      9.000000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [35]:
df

    product  price  stock rating
0    Laptop   1200             8
1     Mouse     25             9
2  Keyboard     75             7
3   Monitor    300             6
4    Webcam     50             8

In [36]:
df['product'].value_counts()

product
Laptop      1
Mouse       1
Keyboard    1
Monitor     1
Webcam      1
Name: count, dtype: int64

In [37]:
df['product'].value_counts(normalize = True) # Percentage in place of count

product
Laptop      0.2
Mouse       0.2
Keyboard    0.2
Monitor     0.2
Webcam      0.2
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [38]:
df.corr(numeric_only = True)

                 price  stock rating
price         1.000000      0.004398
stock rating  0.004398      1.000000

In [39]:
df['price'].corr(df['stock rating'])

np.float64(0.004397952438151934)

In [40]:
df.cov(numeric_only= True)

                 price  stock rating
price         248562.5           2.5
stock rating       2.5           1.3

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [41]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height

# 2. Sort the data by Score (descending)
# Write your code here

# 3. Get mean, median, mode, and std of numeric columns
# Write your code here

# 4. Use value_counts on Name or any categorical column
# Write your code here

# 5. Compute corr() and cov() for all numeric columns
# Write your code here

In [42]:
data_mini = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'Score': [85, 92, 78, 95, 88],
    'Height': [165, 180, 170, 175, 168]
}
df_mini = pd.DataFrame(data_mini)
display(df_mini)

      Name  Age  Score  Height
0    Alice   24     85     165
1      Bob   27     92     180
2  Charlie   22     78     170
3    David   32     95     175
4      Eve   29     88     168

In [43]:
df_mini.sort_values(by = 'Score', ascending = False)

      Name  Age  Score  Height
3    David   32     95     175
1      Bob   27     92     180
4      Eve   29     88     168
0    Alice   24     85     165
2  Charlie   22     78     170

In [44]:
# 3. Get mean, median, mode, and std of numeric columns
# Write your code here

df_mini.mean(numeric_only = True)

Age        26.8
Score      87.6
Height    171.6
dtype: float64

In [45]:
df_mini.median(numeric_only = True)

Age        27.0
Score      88.0
Height    170.0
dtype: float64

In [46]:
df_mini.mode()

      Name  Age  Score  Height
0    Alice   22     78     165
1      Bob   24     85     168
2  Charlie   27     88     170
3    David   29     92     175
4      Eve   32     95     180

In [47]:
df_mini.std(numeric_only = True)

Age       3.962323
Score     6.580274
Height    5.941380
dtype: float64

In [48]:
# 4. Use value_counts on Name or any categorical column
# Write your code here

df_mini['Name'].value_counts()

Name
Alice      1
Bob        1
Charlie    1
David      1
Eve        1
Name: count, dtype: int64

In [49]:
# 5. Compute corr() and cov() for all numeric columns
# Write your code here

df_mini.corr(numeric_only = True)

             Age     Score    Height
Age     1.000000  0.897474  0.399292
Score   0.897474  1.000000  0.595970
Height  0.399292  0.595970  1.000000

In [50]:
df_mini.cov(numeric_only = True)

         Age  Score  Height
Age     15.7   23.4     9.4
Score   23.4   43.3    23.3
Height   9.4   23.3    35.3

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.