# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [12]:
import pandas as pd

# Create a dictionary with some sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Maths': [85, 78, 92, 65, 70],
    'Science': [90, 82, 88, 75, 68],
    'EVS': [70, 60, 75, 80, 85],
    'History': [75, 85, 68, 90, 72]
}

# Create the DataFrame from the dictionary
marks = pd.DataFrame(data)

# Display the first 5 rows of the DataFrame
display(marks.head())

      Name  Maths  Science  EVS  History
0    Alice     85       90   70       75
1      Bob     78       82   60       85
2  Charlie     92       88   75       68
3    David     65       75   80       90
4      Eve     70       68   85       72

In [13]:
marks['Total_Marks'] = marks[['Maths','Science','EVS','History']].apply(sum, axis=1)
display(marks.head())

# apply(lambda row : row.sum(), axis = 1)

      Name  Maths  Science  EVS  History  Total_Marks
0    Alice     85       90   70       75          320
1      Bob     78       82   60       85          305
2  Charlie     92       88   75       68          323
3    David     65       75   80       90          310
4      Eve     70       68   85       72          295

In [14]:
col_Mean = marks[['Maths','Science','EVS','History']].apply(lambda col : col.mean(), axis=0)
col_Mean

Maths      78.0
Science    80.6
EVS        74.0
History    78.0
dtype: float64

In [15]:
# Applying custom function to adataframe

def get_grade(marks):
    if marks >= 90:
        return 'A'
    elif marks >= 80:
      return 'B'
    elif marks >= 70:
      return 'C'
    elif marks >= 60:
      return 'D'
    elif marks >= 50:
      return 'E'
    else:
      return 'F'


marks['Grade'] = marks['Total_Marks'].apply(get_grade)
display(marks.head())

      Name  Maths  Science  EVS  History  Total_Marks Grade
0    Alice     85       90   70       75          320     A
1      Bob     78       82   60       85          305     A
2  Charlie     92       88   75       68          323     A
3    David     65       75   80       90          310     A
4      Eve     70       68   85       72          295     A

In [16]:
# map() is for applying functions element-wise to a Series.

def grace(marks):
  marks = marks + 15
  return marks

marks['Maths'] = marks['Maths'].map(grace)
display(marks.head())

      Name  Maths  Science  EVS  History  Total_Marks Grade
0    Alice    100       90   70       75          320     A
1      Bob     93       82   60       85          305     A
2  Charlie    107       88   75       68          323     A
3    David     80       75   80       90          310     A
4      Eve     85       68   85       72          295     A