# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [94]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)

In [95]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [96]:
b.isnull() #isna and isnull are same.
           # They detect missing or null values

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [97]:
b.isna()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [98]:
b.isna().sum() # Give the sum of missing values in each column

Name     0
Age      2
City     1
Score    1
dtype: int64

In [99]:
b.dropna() # Drop rows with missing values
           # We can use inplace = True/False

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

In [100]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [101]:
b['Age'] = b['Age'].fillna(b['Age'].mean())
b['City'] = b['City'].fillna("Unknown")
b['Score'] = b['Score'].fillna(b['Score'].median())
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000    Unknown   89.5
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [102]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [103]:
# astype() - Change datatype of the column elements

b['Score'] = b['Score'].astype(float) # int to float
b

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [104]:
a = b.copy()
a['Score'] = a['Score'].astype(bool) # float to boolean
a

      Name  Age  Score
0    Alice   25   True
1      Bob   30   True
2  Charlie   35   True
3    David   40   True
4     Emma   22   True

In [118]:
a['Age'] = a['Age'].astype("category") # int to categorical type
a

      Name Age  Score
0    Alice  25   True
1      Bob  30   True
2  Charlie  35   True
3    David  40   True
4     Emma  22   True

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [105]:
c = b.copy()
c['Name'] = c['Name'].replace('Alice', 'Alex')
c

      Name  Age  Score
0     Alex   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [106]:
# Replace using dictionary
d = b.copy()
d['Name'] = d['Name'].replace({'Alice': 'Alex', 'Bob': 'Ben'})
d

      Name  Age  Score
0     Alex   25   88.0
1      Ben   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [107]:
# drop(labels, axis=0) → drop rows by index labels.
# drop(labels, axis=1) → drop columns by name.

# axis 0 = rows
# axis 1 = columns
# default axis = 0 (rows)

In [108]:
e = b.copy()
e

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [109]:
e.drop('Name', axis=1) # inplace = False

   Age  Score
0   25   88.0
1   30   92.0
2   35   79.0
3   40   85.0
4   22   95.0

In [110]:
e.drop([1,3]) # inplace = False

      Name  Age  Score
0    Alice   25   88.0
2  Charlie   35   79.0
4     Emma   22   95.0

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [113]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85

In [114]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [116]:
df.drop_duplicates(inplace = True)
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [121]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

p = pd.DataFrame(data)

print("Original messy DataFrame:")
print(p)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [122]:
p

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [129]:
# 1. Convert 'Age' to numeric, coercing non-numeric values (including None) to NaN
p['Age'] = pd.to_numeric(p['Age'], errors='coerce')

# 2. Fill the NaN values in 'Age' with the mean of the column
p['Age'] = p['Age'].fillna(p['Age'].mean())

# 3. Now that there are no NaNs and all values are numeric, convert to int
p['Age'] = p['Age'].astype(int)

# Also handle missing values in 'Score' and 'Name' if they exist, as per mini-practice
p['Score'] = p['Score'].fillna(p['Score'].median())
p['Name'] = p['Name'].fillna('Unknown')

# 3. Change data types
# Convert Age to int, Score to float, etc.
p['Score'] = p['Score'].astype(float)

p

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai   85.0     y
2   Chrlie   30        Pun   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [130]:
# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed
p['City'] = p['City'].replace('Pun', 'Pune')
p

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai   85.0     y
2   Chrlie   30       Pune   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [136]:
p.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [135]:
# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

p.drop_duplicates()

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai   85.0     y
2   Chrlie   30       Pune   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.