# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [47]:
import pandas as pd

# Create another DataFrame with the same columns as 'df'
data_b = {
    'Name': ['Mia', 'Noah', 'Olivia', 'Paul', 'Quinn'],
    'Age': [26, 32, 29, 31, 27],
    'City': ['London', 'Paris', 'New York', 'Delhi', 'Mumbai'],
    'Score': [88, 91, 79, 85, 93]
}
a = pd.DataFrame(data_b)
display(a.head())   # Aanother way to print a DataFrame

     Name  Age      City  Score
0     Mia   26    London     88
1    Noah   32     Paris     91
2  Olivia   29  New York     79
3    Paul   31     Delhi     85
4   Quinn   27    Mumbai     93

In [48]:
# Use comparison operators to build conditions (e.g., df['col'] > 50).
# Boolean Indexing

a['Age'] > 30

0    False
1     True
2    False
3     True
4    False
Name: Age, dtype: bool

In [49]:
# Pass the condition inside df[...] to get matching rows.

a[a['Age'] > 30]

   Name  Age   City  Score
1  Noah   32  Paris     91
3  Paul   31  Delhi     85

In [50]:
# Combine multiple conditions with & (AND), | (OR), and ~ (NOT).
# Parentheses are required when combining conditions.

a[(a['Age'] > 30) & (a['Score'] > 85)] # And (&)

   Name  Age   City  Score
1  Noah   32  Paris     91

In [51]:
a[(a['Age'] > 30) | (a['Score'] > 85)] # Or (|)

    Name  Age    City  Score
0    Mia   26  London     88
1   Noah   32   Paris     91
3   Paul   31   Delhi     85
4  Quinn   27  Mumbai     93

In [52]:
a[~ (a['Age'] > 30)]

     Name  Age      City  Score
0     Mia   26    London     88
2  Olivia   29  New York     79
4   Quinn   27    Mumbai     93

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [53]:
a.query('Age > 30') # Condition must be in Strings

   Name  Age   City  Score
1  Noah   32  Paris     91
3  Paul   31  Delhi     85

In [54]:
Cond = 30
a.query('Age > @Cond') # "@" will access the value of cond

   Name  Age   City  Score
1  Noah   32  Paris     91
3  Paul   31  Delhi     85

In [55]:
a.query('Age > 30 and Score > 85') # multipke conditions using "and", "or", "not". Can't use symbols

   Name  Age   City  Score
1  Noah   32  Paris     91

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [56]:
a

     Name  Age      City  Score
0     Mia   26    London     88
1    Noah   32     Paris     91
2  Olivia   29  New York     79
3    Paul   31     Delhi     85
4   Quinn   27    Mumbai     93

In [57]:
a['Name'].str.lower()

0       mia
1      noah
2    olivia
3      paul
4     quinn
Name: Name, dtype: object

In [58]:
a["City"].str.upper()

0      LONDON
1       PARIS
2    NEW YORK
3       DELHI
4      MUMBAI
Name: City, dtype: object

In [59]:
a['City'].str.contains('a', case = False)

0    False
1     True
2    False
3    False
4     True
Name: City, dtype: bool

In [62]:
a['Name'].str.replace('Mia','Marry')

0     Marry
1      Noah
2    Olivia
3      Paul
4     Quinn
Name: Name, dtype: object

In [63]:
a['City'].str.startswith('D')

0    False
1    False
2    False
3     True
4    False
Name: City, dtype: bool

In [64]:
a['Name'].str.endswith('a')

0     True
1    False
2     True
3    False
4    False
Name: Name, dtype: bool

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [61]:


# 1. Build a DataFrame with columns: Name, Age, City, Score
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Age': [24, 30, 35, 28, 22, 45, 30, 29, 38, 25],
    'City': ['New York', 'Los Angeles', 'Delhi', 'Mumbai', 'London', 'Paris', 'Delhi', 'New York', 'Mumbai', 'London'],
    'Score': [90, 85, 78, 92, 88, 70, 95, 80, 87, 75]
}
df = pd.DataFrame(data)
display(df.head())

# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

      Name  Age         City  Score
0    Alice   24     New York     90
1      Bob   30  Los Angeles     85
2  Charlie   35        Delhi     78
3    David   28       Mumbai     92
4      Eve   22       London     88

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.