# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [2]:
import pandas as pd
import numpy as np

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [3]:
a = [10,20,30,40]
s = pd.Series(a) # This will give a one-dimensional series
                 # 0,1,2,3 are columns and 0/marks is the only row
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
s1 = pd.Series(a,name = "Marks")
s1

0    10
1    20
2    30
3    40
Name: Marks, dtype: int64

Dictionary to Series

In [ ]:
d = {'susu':90, 'meethu':87, 'PC':100}
s = pd.Series(d, name = 'Marks')
s

susu      90
meeth     87
PC       100
Name: Marks, dtype: int64

In [13]:
d = {'susu':90, 'meeth':87, 'PC':100}
s = pd.Series(d, name = 'Marks')
print(s)

susu      90
meeth     87
PC       100
Name: Marks, dtype: int64

### Creating a DataFrame

In [17]:
d = {"Name":['susu','meeth','PC'],
     "Marks":[90,87,100],
     "Subject":['Maths','Social','Tecch']}
df = pd.DataFrame(d)

print(df)

    Name  Marks Subject
0   susu     90   Maths
1  meeth     87  Social
2     PC    100   Tecch

In [18]:
d = {"Name":['susu','meeth','PC'],
     "Marks":[90,87,100],
     "Subject":['Maths','Social','Tecch']}
df = pd.DataFrame(d)
df

    Name  Marks Subject
0   susu     90   Maths
1  meeth     87  Social
2     PC    100   Tecch

### Creating DataFrame from NumPy Arrays

In [19]:
a = np.arange(10,100,10).reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
d = pd.DataFrame(a, columns = ['A','B','C'])
d

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.