# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [3]:
import pandas as pd

data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['HR', 'IT', 'HR', 'Finance', 'IT'],
    'Salary': [60000, 75000, 62000, 80000, 78000]
}
df = pd.DataFrame(data)
display(df.head())

  Employee Department  Salary
0    Alice         HR   60000
1      Bob         IT   75000
2  Charlie         HR   62000
3    David    Finance   80000
4      Eve         IT   78000

In [6]:
df[df["Department"] == "IT"]["Salary"].mean()

np.float64(75000.0)

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [7]:
df.groupby('Department')['Salary'].mean()

Department
Finance      82500.000000
HR           62333.333333
IT           75000.000000
Marketing    71500.000000
Name: Salary, dtype: float64

In [8]:
df.groupby('Department')['Employee'].count()

Department
Finance      2
HR           3
IT           3
Marketing    2
Name: Employee, dtype: int64

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [11]:
df.groupby('Department')['Salary'].agg(["mean","max","min"])

                    mean    max    min
Department
Finance     82500.000000  85000  80000
HR          62333.333333  65000  60000
IT          75000.000000  78000  72000
Marketing   71500.000000  73000  70000

In [9]:
df.groupby('Department').agg({'Salary':'mean', 'Employee':'count'})

                  Salary  Employee
Department
Finance     82500.000000         2
HR          62333.333333         3
IT          75000.000000         3
Marketing   71500.000000         2

In [10]:
df.groupby('Department').agg({'Salary':['mean', 'max'], 'Employee':'count'})

                  Salary        Employee
                    mean    max    count
Department
Finance     82500.000000  85000        2
HR          62333.333333  65000        3
IT          75000.000000  78000        3
Marketing   71500.000000  73000        2

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [12]:
df

  Department Employee  Salary  Age         City
0         HR    Alice   60000   30     New York
1         IT      Bob   75000   35  Los Angeles
2         HR  Charlie   62000   28      Chicago
3    Finance    David   80000   40      Houston
4         IT      Eve   78000   32      Phoenix
5  Marketing    Frank   70000   29     New York
6    Finance    Grace   85000   45  Los Angeles
7         HR    Heidi   65000   31      Chicago
8         IT     Ivan   72000   38      Houston
9  Marketing     Judy   73000   27      Phoenix

In [13]:
# pivot_table() summarizes data like Excel pivot tables.

df.pivot_table(values='Salary', index='Department', aggfunc='mean')

                  Salary
Department
Finance     82500.000000
HR          62333.333333
IT          75000.000000
Marketing   71500.000000

In [14]:
df.pivot_table(values=['Salary','Age'], index='Department', aggfunc='mean')

                  Age        Salary
Department
Finance     42.500000  82500.000000
HR          29.666667  62333.333333
IT          35.000000  75000.000000
Marketing   28.000000  71500.000000

In [19]:
import seaborn as sns

df = sns.load_dataset('flights')

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [24]:
import seaborn as sns

df = sns.load_dataset('flights')
df['year'].value_counts()

year
1949    12
1950    12
1951    12
1952    12
1953    12
1954    12
1955    12
1956    12
1957    12
1958    12
1959    12
1960    12
Name: count, dtype: int64

In [26]:
df.pivot_table(values='passengers', index='year', columns='month', aggfunc='mean')

/tmp/ipykernel_755/2079124833.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values='passengers', index='year', columns='month', aggfunc='mean')

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [27]:
# crosstab() shows frequency counts of combinations of factors


data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['HR', 'IT', 'HR', 'Finance', 'IT'],
    'Salary': [60000, 75000, 62000, 80000, 78000]
}
df = pd.DataFrame(data)
display(df.head())

  Employee Department  Salary
0    Alice         HR   60000
1      Bob         IT   75000
2  Charlie         HR   62000
3    David    Finance   80000
4      Eve         IT   78000

In [29]:
df['AgeGroup'] = pd.cut(df['Salary'], bins=[60000,70000,80000,90000], labels=['Low','Medium','High'])
df

  Employee Department  Salary AgeGroup
0    Alice         HR   60000      NaN
1      Bob         IT   75000   Medium
2  Charlie         HR   62000      Low
3    David    Finance   80000   Medium
4      Eve         IT   78000   Medium

In [30]:
pd.crosstab(df['Department'], df['AgeGroup'])

AgeGroup    Low  Medium
Department
Finance       0       1
HR            1       0
IT            0       2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [5]:
import pandas as pd

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
data = {
    'Department': ['HR', 'IT', 'HR', 'Finance', 'IT', 'Marketing', 'Finance', 'HR', 'IT', 'Marketing'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Salary': [60000, 75000, 62000, 80000, 78000, 70000, 85000, 65000, 72000, 73000],
    'Age': [30, 35, 28, 40, 32, 29, 45, 31, 38, 27],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data)
display(df.head())

# 2. Group by Department to get average Salary and max Age
dept_salary_age = df.groupby('Department').agg(Avg_Salary=('Salary', 'mean'), Max_Age=('Age', 'max'))
display(dept_salary_age)

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age, and count of employees per Department
multi_agg = df.groupby('Department').agg(
    Avg_Salary=('Salary', 'mean'),
    Max_Age=('Age', 'max'),
    Employee_Count=('Employee', 'count')
)
display(multi_agg)

# 4. Create a pivot_table to see mean Salary by Department and City
pivot_table_salary = pd.pivot_table(df, values='Salary', index='Department', columns='City', aggfunc='mean')
display(pivot_table_salary)

# 5. Build a crosstab for Department vs City
crosstab_dept_city = pd.crosstab(df['Department'], df['City'])
display(crosstab_dept_city)

  Department Employee  Salary  Age         City
0         HR    Alice   60000   30     New York
1         IT      Bob   75000   35  Los Angeles
2         HR  Charlie   62000   28      Chicago
3    Finance    David   80000   40      Houston
4         IT      Eve   78000   32      Phoenix

              Avg_Salary  Max_Age
Department
Finance     82500.000000       45
HR          62333.333333       31
IT          75000.000000       38
Marketing   71500.000000       29

              Avg_Salary  Max_Age  Employee_Count
Department
Finance     82500.000000       45               2
HR          62333.333333       31               3
IT          75000.000000       38               3
Marketing   71500.000000       29               2

City        Chicago  Houston  Los Angeles  New York  Phoenix
Department
Finance         NaN  80000.0      85000.0       NaN      NaN
HR          63500.0      NaN          NaN   60000.0      NaN
IT              NaN  72000.0      75000.0       NaN  78000.0
Marketing       NaN      NaN          NaN   70000.0  73000.0

City        Chicago  Houston  Los Angeles  New York  Phoenix
Department
Finance           0        1            1         0        0
HR                2        0            0         1        0
IT                0        1            1         0        1
Marketing         0        0            0         1        1

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.