# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [2]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b.head(2) # First 2 rows

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92

In [3]:
b.head(10) # 10 > no. of rows in table (4), It gave only 4 rows which are originally available

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [4]:
b.tail(2) # Last two rows

    Name  Age  Score
3  David   40     85
4   Emma   22     95

In [5]:
b.tail(10)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [8]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [11]:
print(b,'\n')
print(b.shape) # (rows, columns)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

(5, 3)

In [13]:
b.dtypes # here dtypes is used because we need to check for multiple rows

Name     object
Age       int64
Score     int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [15]:

print(b)
b['Name'] # single column selection

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object

In [18]:
print(b)
b[['Name','Score']] # Multiple columns selection with "FANCY INDEXING"

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79
3    David     85
4     Emma     95

In [22]:
# Label-based selection → df.loc[row_label, col_label]
print(b)
b.loc[0]

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

Name     Alice
Age         25
Score       88
Name: 0, dtype: object

In [23]:
type(b.loc[0]) # Its a series

pandas.core.series.Series

In [24]:
print(b)
b.loc[0,'Name'] # It will select single element in row = 0, column = Name

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

'Alice'

In [26]:
b.loc[0:3,['Name','Age']] #

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [27]:
# Index based selection, It will select 0th row
b.iloc[0]

Name     Alice
Age         25
Score       88
Name: 0, dtype: object

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [28]:
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [30]:
b.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
b.columns

Index(['Name', 'Age', 'Score'], dtype='object')

In [32]:
b.values

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [35]:
b
c = b.rename(columns={'Score':'Marks'})
c

      Name  Age  Marks
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [36]:
b.rename(columns = {"Score":"Marks"}, inplace = True)  # inplace = True will make changes to the original DataFrame
                                                       # inplace = False will make changes in the copy, not in original DataFrame
b

      Name  Age  Marks
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [55]:
c = b.reset_index(inplace=False) # Reset the index to make 'Name' a column again
c

      Name  Age  Marks
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [56]:
a = b.reset_index(inplace=False) # Reset the index to make 'Name' a column again
a = a.set_index('Name', inplace=False) # Now 'Name' can be set as the index
a

         Age  Marks
Name
Alice     25     88
Bob       30     92
Charlie   35     79
David     40     85
Emma      22     95

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [ ]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)

# Show the first 3 rows, last 2 rows, and info
# your code here

# Select a sub-DataFrame with only 2 columns
# your code here

# Rename one column and set any column as index, then reset it back
# your code here

# Print df.shape, df.dtypes, and df.columns
# your code here

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).

In [45]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)
df

      Name  Age       City  Score
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [46]:
# Show the first 3 rows, last 2 rows, and info
df.head(3)

      Name  Age    City  Score
0    Alice   25   Delhi     85
1      Bob   30  Mumbai     91
2  Charlie   35    Pune     78

In [47]:
df.tail(2)

    Name  Age       City  Score
3  David   40  Bangalore     88
4   Emma   22    Chennai     95

In [48]:
# Select a sub-DataFrame with only 2 columns
# Fancy Indexing
df[['Name','Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

In [49]:
# Rename one column and set any column as index, then reset it back
df.rename(columns = {"Score":"Marks"}, inplace = True)
df

      Name  Age       City  Marks
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [72]:
d = df.reset_index(inplace=True)
d

In [73]:
df

        City     Name  Age  Marks
0      Delhi    Alice   25     85
1     Mumbai      Bob   30     91
2       Pune  Charlie   35     78
3  Bangalore    David   40     88
4    Chennai     Emma   22     95

In [75]:
a = df.set_index("City", inplace = False)
a

              Name  Age  Marks
City
Delhi        Alice   25     85
Mumbai         Bob   30     91
Pune       Charlie   35     78
Bangalore    David   40     88
Chennai       Emma   22     95

In [76]:
df

        City     Name  Age  Marks
0      Delhi    Alice   25     85
1     Mumbai      Bob   30     91
2       Pune  Charlie   35     78
3  Bangalore    David   40     88
4    Chennai     Emma   22     95