# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [1]:
import pandas as pd

In [2]:
# Dataset 1: Product details
df1 = pd.DataFrame({
    'Product_ID': [1, 2, 3, 4],
    'Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [1200, 25, 75, 300]
})
display(df1)

# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2 = pd.DataFrame({
    'Product_ID': [5, 6, 7],
    'Name': ['Webcam', 'Microphone', 'Headphones'],
    'Price': [50, 100, 150]
})
display(df2)

# Dataset 3: Additional info (different columns → good for horizontal stacking)
df3 = pd.DataFrame({
    'Product_ID': [1, 2, 3, 5],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Stock': [100, 200, 150, 80]
})
display(df3)

   Product_ID      Name  Price
0           1    Laptop   1200
1           2     Mouse     25
2           3  Keyboard     75
3           4   Monitor    300

   Product_ID        Name  Price
0           5      Webcam     50
1           6  Microphone    100
2           7  Headphones    150

   Product_ID     Category  Stock
0           1  Electronics    100
1           2  Electronics    200
2           3  Electronics    150
3           5  Electronics     80

In [5]:
pd.concat([df1, df2], axis=0, ignore_index=True)

   Product_ID        Name  Price
0           1      Laptop   1200
1           2       Mouse     25
2           3    Keyboard     75
3           4     Monitor    300
4           5      Webcam     50
5           6  Microphone    100
6           7  Headphones    150

In [6]:
pd.concat([df1, df3],) # By default axis = 0

   Product_ID      Name   Price     Category  Stock
0           1    Laptop  1200.0          NaN    NaN
1           2     Mouse    25.0          NaN    NaN
2           3  Keyboard    75.0          NaN    NaN
3           4   Monitor   300.0          NaN    NaN
0           1       NaN     NaN  Electronics  100.0
1           2       NaN     NaN  Electronics  200.0
2           3       NaN     NaN  Electronics  150.0
3           5       NaN     NaN  Electronics   80.0

In [10]:
display(df1)
display(df3)

   Product_ID      Name  Price
0           1    Laptop   1200
1           2     Mouse     25
2           3  Keyboard     75
3           4   Monitor    300

   Product_ID     Category  Stock
0           1  Electronics    100
1           2  Electronics    200
2           3  Electronics    150
3           5  Electronics     80

In [9]:
pd.concat([df1, df3], axis=1, ignore_index= False)

   Product_ID      Name  Price  Product_ID     Category  Stock
0           1    Laptop   1200           1  Electronics    100
1           2     Mouse     25           2  Electronics    200
2           3  Keyboard     75           3  Electronics    150
3           4   Monitor    300           5  Electronics     80

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [11]:
product = pd.concat([df1, df2], axis=0, ignore_index=True)
display(product)

   Product_ID        Name  Price
0           1      Laptop   1200
1           2       Mouse     25
2           3    Keyboard     75
3           4     Monitor    300
4           5      Webcam     50
5           6  Microphone    100
6           7  Headphones    150

In [16]:
sales = pd.DataFrame({
    "Product_ID": [1, 2, 3, 4,],
    "Quantity sold": [5, 10, 15, 20]
})
display(sales)

   Product_ID  Quantity sold
0           1              5
1           2             10
2           3             15
3           4             20

In [30]:
# On = to choose the columns

pd.merge(product, sales, left_on = "Product_ID", right_on="Product_ID")

   Product_ID      Name  Price  Quantity sold
0           1    Laptop   1200              5
1           2     Mouse     25             10
2           3  Keyboard     75             15
3           4   Monitor    300             20

In [17]:
pd.merge(product, sales, on = "Product_ID", how= "inner") # Include common IDs

   Product_ID      Name  Price  Quantity sold
0           1    Laptop   1200              5
1           2     Mouse     25             10
2           3  Keyboard     75             15
3           4   Monitor    300             20

In [20]:
pd.merge(product, sales, on = "Product_ID", how= "outer") # Inculde every thing

   Product_ID        Name  Price  Quantity sold
0           1      Laptop   1200            5.0
1           2       Mouse     25           10.0
2           3    Keyboard     75           15.0
3           4     Monitor    300           20.0
4           5      Webcam     50            NaN
5           6  Microphone    100            NaN
6           7  Headphones    150            NaN

In [19]:
pd.merge(product, sales, on = "Product_ID", how= "right") # Focus on right table (sales)

   Product_ID      Name  Price  Quantity sold
0           1    Laptop   1200              5
1           2     Mouse     25             10
2           3  Keyboard     75             15
3           4   Monitor    300             20

In [18]:
pd.merge(product, sales, on = "Product_ID", how= "left") # Focus on left table (product)

   Product_ID        Name  Price  Quantity sold
0           1      Laptop   1200            5.0
1           2       Mouse     25           10.0
2           3    Keyboard     75           15.0
3           4     Monitor    300           20.0
4           5      Webcam     50            NaN
5           6  Microphone    100            NaN
6           7  Headphones    150            NaN

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [23]:
stock = pd.DataFrame({
    "Stock": [115, 220, 356, 224]
}, index = [1, 2, 3, 5])
display(stock)

   Stock
1    115
2    220
3    356
5    224

In [26]:
df = product.set_index("Product_ID")
display(df)

                  Name  Price
Product_ID
1               Laptop   1200
2                Mouse     25
3             Keyboard     75
4              Monitor    300
5               Webcam     50
6           Microphone    100
7           Headphones    150

In [29]:
df.join(stock, how = "inner") # outer, left, right can also be used

       Name  Price  Stock
1    Laptop   1200    115
2     Mouse     25    220
3  Keyboard     75    356
5    Webcam     50    224

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [ ]:

# 1. Create three DataFrames: Products, Sales, and Revenue

# 2. Concatenate them vertically and horizontally
# Write your code here

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here

# 4. Join Products with Sales based on index or a key
# Write your code here

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.